### PR TITLE
fix(docker): set entrypoint to slice{""}

### PR DESCRIPTION
**Pull request by thesayyn**

### CODE REVIEW

**Comment by thesayyn** [comment]
Seems like there is no consensus between podman and docker about how the entry point should be set. I am open for other solutions as well.  

Ref: https://github.com/moby/moby/issues/23498 , https://github.com/containers/podman/issues/6935

**Comment by loosebazooka** [comment]
It looks like this has an error in the github workflow file

> [Invalid workflow file: .github/workflows/integration-tests.yml#L14](https://github.com/GoogleContainerTools/container-structure-test/actions/runs/2949558816/workflow)
The workflow is not valid. .github/workflows/integration-tests.yml (Line: 14, Col: 5): Unexpected value 'matrix'

**Comment by thesayyn** [comment]
pushed a fix. should be ready now.

**Comment by thesayyn** [comment]
tests are yielding false positives. I'll fix them

**Comment by loosebazooka** [comment]
hrmm.. looks like my merge messed thing up somehow?

**Comment by loosebazooka** [comment]
might need to clear the merge and do a rebase (my bad)

**Comment by loosebazooka** [comment]
yeah weirdly the merge change the permissions of the file `100755 → 100644`. Wonder why it did that.

**Review by loosebazooka — APPROVED** [review]

**Pull request merged**
