### PR TITLE
docs: add homebrew install guide

### PR DESCRIPTION
**Pull request by chenrui333**
relates to #286

```
$ brew install container-structure-test
...
🍺  /usr/local/Cellar/container-structure-test/1.10.0: 6 files, 12.8MB
```

```
$ container-structure-test
container-structure-test provides a powerful framework to validate
the structure of a container image.
These tests can be used to check the output of commands in an image,
as well as verify metadata and contents of the filesystem.
```

cc @wndhydrnt @nkubala

### CODE REVIEW

**Review by nkubala — APPROVED** [review]
nice. the formula is out of date though (still on v1.10.0), will it be kept up to date?

**Comment by chenrui333** [comment]
@nkubala The issue is with the release tag, currently the release is still with `pre-release`  so due to the homebrew-core policy, we could not merge it.

- I actually have already filed the update PR, https://github.com/Homebrew/homebrew-core/pull/89139

**Comment by chenrui333** [comment]
If you can update the tag today, we can reopen the PR and make it to the latest release.

**Comment by nkubala** [comment]
ahh right right, I wanted to verify an issue was fixed before publishing. should be done now

**Comment by chenrui333** [comment]
Gonna reopen the PR and we can merge after today.

**Pull request merged**
