### PR TITLE
Add stdout and stderr to JUnit test results

### PR DESCRIPTION
**Pull request by ddl-pjohnson**
Add the contents of stdout and stderr when creating junit test results.

I'm not sure if there is a formal definition of junit, so I followed https://github.com/testmoapp/junitxml and it seems to work in CircleCI.

(I couldn't see a pull request template, I'll be happy to add anything necessary)

### CODE REVIEW

**Comment by coopernetes** [comment]
Tested this on Jenkins, nice :+1: 

image

image

**Comment by loosebazooka** [comment]
can you sign the CLA before we try to merge this?

**Comment by loosebazooka** [comment]
@ddl-pjohnson are you still able to help get this merged?
need a rebase and a CLA signing

**Comment by ddl-pjohnson** [comment]
@loosebazooka sorry for the delay, our company has now signed the CLA.

**Review by loosebazooka — APPROVED** [review]

**Pull request merged**
