### PR TITLE
fix(windows): make remaining paths use rlocation

### PR DESCRIPTION
**Pull request by alexeagle**
I think this is the last missing code change to get rules_oci bcr test green on Windows.

Note, we'll still need a release of the binaries in this repo, and then another change to mirror those into repositories.bzl.

### CODE REVIEW

**Review by thesayyn — APPROVED** [review]

**Comment by timonwong** [comment]
@alexeagle It seems this PR reverts the work in #347? After upgrading I hit error like this:

```
Error: error creating driver: processing tar image reference: mkdir /var/folders/nh/494h__wn4rq_wr68cr5qn9sh0000gn/T/privatevartmp_bazel_timonwongf8e522ad4eb28d0876e69e8716848e79execrootio_alauda_asm_asmbazel-outdarwin_arm64-optbincmdglobal-asm-controllerimage-test.linux_amd64.sh.runfilesio_alauda_asm_asmcmdglobal-asm-controllerimage.tar.linux_amd64tarball.tar@sha256:fac37afd164231cb790e21192377d9ae6120fa1e2b96108be747a83b060d0586517621879: file name too long

```

**Comment by alexeagle** [comment]
@timonwong that error was fixed in https://github.com/GoogleContainerTools/container-diff/pull/395#issuecomment-1646927603

and brought to this repo in https://github.com/GoogleContainerTools/container-structure-test/commit/8b6e083b3680ec08adea46dc14a349ee2d3e8da9

**Comment by timonwong** [comment]
@alexeagle I don't know why it's stopped working, previously I'm using your fork, after I changed cst to v1.16.0 it shows "file name too long error" again:


```
    container_structure_test = dict(
        sha256 = "2da13da4c4fec9d4627d4084b122be0f4d118bd02dfa52857ff118fde88e4faa",
        version = "1.16.0",
        strip_prefix = "container-structure-test-{version}",
        urls = [
            "https://github.com/GoogleContainerTools/container-structure-test/archive/v{version}.zip",
        ],
    ),
```

Previously:

```
    container_structure_test = dict(
        sha256 = "6913d8b5fa701b07d30ca236d2ab9e456ea0da415266cd8910a4537fb9222445",
        version = "e5848342114f9a435e9a54f45bef99a7703c9173",
        strip_prefix = "container-structure-test-{version}",
        urls = [
            "https://github.com/GoogleContainerTools/container-structure-test/archive/{version}.zip",
        ],
    ),
```

**Comment by timonwong** [comment]
@alexeagle Ooops, finally figured out it's because the v1.16.0 tag on 8113400cd351d18dbce687e400fcd9434088976d does not contains actual binaries in 18d9b2bcd2cbee1ab8df7c232ef6b7cddff9708a

I have to update my bazel repository accordingly:

```
    container_structure_test = dict(
        sha256 = "620a7223a0f10434b12c34271bc0086655375c2dca024fc372bd9f1838e5307b",
        version = "aa025d1c83d95a27a367d4e5df9bb1dc67c1f3e8",
        strip_prefix = "container-structure-test-{version}",
        urls = [
            "https://github.com/GoogleContainerTools/container-structure-test/archive/{version}.zip",
        ],
    ),
```

**Comment by alexeagle** [comment]
Err yeah... sorry! We have a fix for that now so the next release won't have that problem

**Pull request merged**
