### PR TITLE
Use Lstat() Instead of Stat()

### PR DESCRIPTION
**Pull request by midnightconman**
This PR switches the tar driver from using `os.Stat()` to `os.Lstat()`... this enables symlink file existence testing with the tar driver.

If tests are needed, please let me know... I verified functionality manually (via testing existence of symlinks in a docker image).

### CODE REVIEW

**Comment by midnightconman** [comment]
@googlebot I signed it!

**Comment by nkubala** [comment]
@midnightconman any update here? I'd be happy to merge this with a test.

**Comment by charlyx** [comment]
@midnightconman Hi, do you need help with test? I'd be more than happy to help.

@nkubala How can I help? should I open a new PR with missing test?

**Comment by nkubala** [comment]
@charlyx thanks for jumping in. if @midnightconman can give you write access to their branch, you could simply update this PR and we could merge it, but i'm not sure that will happen in a timely manner.

if you'd like to open a PR with a test and reference it in this one, we can just merge both.

**Pull request closed without merging**
