### PR TITLE
Cleaning and improving log sentences.

### PR DESCRIPTION
**Pull request by SMSadegh19**
Hi!
I was searching about Good-First-Issues in Go language, so I found this repo.

I tried to read the source code and I was thinking that what can I do.

I saw in the source code most of log sentences start with Uppercase alphabet, But few of them start with lowercase.
So I made it clean and made this PR with Love.❤️

If any other Good-First-Issue you have in this repository please tell me.
Thanks a lot!

### CODE REVIEW

**Comment by SMSadegh19** [comment]
@nkubala

**Review by loosebazooka — APPROVED** [review]

**Comment by loosebazooka** [comment]
hrmm, this might need a rebase... @SMSadegh19 ?

**Comment by SMSadegh19** [comment]
I don't know. I forgot everything about this PR after more than one year.

**Comment by loosebazooka** [comment]
lol yeah, there was no really working on it. I can close it if you prefer to not continue the work?

**Comment by SMSadegh19** [comment]
It's OK. Feel free.

**Pull request closed without merging**
